services:
  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol/config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "55679:55679" # zPages (optional for debugging)
    command: ["--config=/etc/otelcol/config.yaml"]

  fluent-bit:
    image: cr.fluentbit.io/fluent/fluent-bit:latest
    container_name: fluent-bit
    depends_on:
      - otel-collector
    volumes:
      - ./:/fluent-bit/etc/
    command: ["fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.conf"]