# fluentBit -> otelCollector -> Signoz
services:
  go-app:
    build:
      context: .
    container_name: go-app
    restart: always
    logging:
      driver: fluentd
      options:
        fluentd-address: host.docker.internal:24224
        tag: go-app
    environment:
      - SERVICE_NAME=demo_otel
      - OTEL_EXPORTER_OTLP_ENDPOINT=signoz-otel-collector:4317
      - INSECURE_MODE=true
    ports:
      - "1323:1323"
    depends_on:
      - fluent-bit
    networks:
      - otel-network

  fluent-bit:
    image: fluent/fluent-bit:latest
    container_name: fluent-bit
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf
    ports:
      - "24224:24224"
    networks:
      - otel-network

networks:
  otel-network:
    external: true