services:
  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol/config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "55679:55679" # zPages (optional for debugging)
    command: ["--config=/etc/otelcol/config.yaml"]

  fluent-bit:
    image: fluent/fluent-bit:4.0
    container_name: fluent-bit
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf
    ports:
      - "24224:24224"
    depends_on:
      - otel-collector
  
  go-app:
    build:
      context: .
    container_name: go-app
    restart: always
    logging:
      driver: fluentd
      options:
        fluentd-address: host.docker.internal:24224
        tag: api
    depends_on:
      - fluent-bit
    ports:
      - "1323:1323"