receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318 #this is for receiving logging from fluent-bit

processors:
  resource:
    attributes:
      - key: service.name
        from_attribute: service.name
        action: upsert
      - key: deployment.environment
        value: "testing"
        action: insert
      - key: host.name
        from_attribute: hostname
        action: upsert

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug]

    logs:  
      receivers: [otlp]
      processors: [resource]
      exporters: [debug]